#Sources
:sources:
  Customer:
  Category:
  Product:
  Order:
  OrderDetail:
    :poll_interval: 300

:development:
  :licensefile: settings/license.key
  :redis: 127.0.0.1:6379
  :syncserver: http://127.0.0.1:9292/api/application

:test:
  :licensefile: settings/license.key
  :redis: 127.0.0.1:6379
  :syncserver: http://127.0.0.1:9292/api/application

:production:
  :licensefile: settings/license.key
  :redis: 127.0.0.1:6379
  :syncserver: http://127.0.0.1:9292/api/application
